kind: pipeline
type: docker
name: build
platform:
  os: linux
  arch: amd64
steps:
  -  name: ZenSpace Build ✨
     image: openjdk:jdk-slim
     commands:
       - cd ./packages/server
       - chmod +ux gradlew
       - ./gradlew build --no-daemon
  -  name: ZenSpace Test 🗒️     
     image: openjdk:jdk-slim
     commands: 
       - cd ./packages/server
       - chmod +ux gradlew
       - ./gradlew check
  -  name: ZenSpace Run ✅
     image: gradle:jdk17
     commands:
       - cd ./packages/server
       - chmod +ux gradlew
       - ./gradlew run --no-daemon
