kind: pipeline
type: docker
name: build
platform:
  os: linux
  arch: amd64
steps:
  - name: ZenSpace Build ✨
    image: gradle:jdk17
    environment:
      PASS:
        from_secret: github-token
    commands:
      - cd ./packages/server
      - chmod +x gradlew
      - ./gradlew jib --image=ghcr.io/brys0/zenspace:latest -Djib.to.auth.username=Brys0 -Djib.to.auth.password=$PASS
