kind: pipeline
type: docker
name: build
platform:
  os: linux
  arch: amd64
steps:
  -  name: ZenSpace ✨
     image: gradle:jdk17
     commands:
       - cd ./packages/server
       - chmod +x gradlew
       - gradle -version
       - ./gradlew build --no-daemon --scan --stacktrace
  -  name: Run ✔
     image: gradle:jdk17
     commands:
       - ./gradlew run --no-daemon
