kind: pipeline
type: docker
name: build
platform:
  os: linux
  arch: amd64
steps:
  -  name: ZenSpace Build ✨
     image: openjdk:jdk-slim
     commands:
       - cd ./packages/server
       - chmod +x gradlew
       - ./gradlew build 
  -  name: ZenSpace Test 🗒️     
     image: openjdk:jdk-slim
     commands: 
       - cd ./packages/server
       - chmod +x gradlew
       - ./gradlew check
  -  name: ZenSpace Build JAR 🏗️
     image: openjdk:jdk-slim
     commands:
       - cd ./packages/server
       - chmod +x gradlew
       - ./gradlew shadowJar
  -  name: ZenSpace Run JAR ✅
     image: openjdk:jdk-slim
     commands: 
       - cd ./packages/server
       - java -jar ./build/lib/zenspaceapi.jar -Xmx2G -Xms500M
