kind: pipeline
type: docker
name: build
platform:
  os: linux
  arch: amd64
steps:
  - name: 🔃 Restore Gradle Cache
    image: meltwater/drone-cache
    pull: true
    settings:
      backend: "filesystem"
      restore: true
      cache_key: "volume"
      archive_format: "gzip"
      mount:
        - "/drone"
    volumes:
      - name: cache
        path: /tmp/cache
  - name: ZenSpace Build ✨
    image: gradle:jdk17
    environment:
      PASS:
        from_secret: github-token
      GRADLE_USER_HOME: /drone
    commands:
      - ls /
      - cd ./packages/server
      - chmod +x gradlew
      - ./gradlew jib --image=ghcr.io/brys0/zenspace:latest -Djib.to.auth.username=Brys0 -Djib.to.auth.password=$PASS
      - ls /drone
  - name: 🏗️ Rebuild Cache
    image: meltwater/drone-cache
    pull: true
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: "volume"
      archive_format: "gzip"
      mount:
        - "/drone"
    volumes:
      - name: cache
        path: /tmp/cache
volumes:
  - name: cache
    host:
      path: /var/lib/cache
trigger:
  branch:
    - pre-alpha
