kind: pipeline
type: docker
name: build
platform:
  os: linux
  arch: amd64
steps:
  - name: 🔃 Restore Gradle Cache
    image: meltwater/drone-cache
    pull: true
    settings:
      backend: "filesystem"
      restore: true
      cache_key: "volume"
      archive_format: "tar"
      mount:
        - "drone"
    volumes:
      - name: cache
        path: /tmp/cache
  - name: 🧪 ZenSpace Test
    image: gradle:jdk17
    failure: ignore
    environment:
      PASS:
        from_secret: github-token
      GRADLE_USER_HOME: /drone/src/drone
    commands:
      - ls /drone
      - cd ./packages/server
      - chmod +x gradlew
      - ./gradlew --no-daemon test 
      - ls /drone/src
  - name: 🏗️ Rebuild Cache
    image: meltwater/drone-cache
    pull: true
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: "volume"
      archive_format: "tar"
      mount:
        - "/drone"
    volumes:
      - name: cache
        path: /tmp/cache
volumes:
  - name: cache
    host:
      path: /var/lib/cache
trigger:
  branch:
    - pre-alpha
