kind: pipeline
type: docker
name: build
platform:
  os: linux
  arch: amd64
steps:
  - name: Debug
    image: openjdk:jdk-slim
    commands:
      - cd ./packages/server
      - ls
      - ls ./build
  - name: ZenSpace Build ✨
    image: openjdk:jdk-slim
    environment:
      PASS:
        from_secret: github-token
    commands:
      - cd ./packages/server
      - chmod +x gradlew
      - ./gradlew jib --image=github.com/Brys0/ZenSpace -Djib.to.auth.username=Brys0 -Djib.to.auth.password=$PASS
