// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeTheme(arg1) {
  return window['go']['app']['App']['ChangeTheme'](arg1);
}

export function DownloadUpdate(arg1) {
  return window['go']['app']['App']['DownloadUpdate'](arg1);
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function HasUser(arg1) {
  return window['go']['app']['App']['HasUser'](arg1);
}

export function PingDelay() {
  return window['go']['app']['App']['PingDelay']();
}

export function PreInit() {
  return window['go']['app']['App']['PreInit']();
}

export function Restart() {
  return window['go']['app']['App']['Restart']();
}

export function SetCurrentUser(arg1) {
  return window['go']['app']['App']['SetCurrentUser'](arg1);
}

export function SetUser(arg1, arg2) {
  return window['go']['app']['App']['SetUser'](arg1, arg2);
}
