// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mocks} from '../models';

export function ChangeTheme(arg1:string):void;

export function DownloadUpdate(arg1:string):Promise<string>;

export function GetConfig():Promise<mocks.AppConfig>;

export function PingDelay():void;

export function PreInit():void;

export function Restart():void;
