// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChangeTheme(arg1:string):void;

export function GetConfig():Promise<main.AppConfig>;

export function Greet(arg1:string):Promise<string>;

export function PreInit():void;
