// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mocks} from '../models';

export function GetChannel(arg1:string):Promise<mocks.Channel>;

export function GetMessagesFromDM(arg1:string,arg2:any,arg3:any):Promise<Array<mocks.Message>>;
