// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DialSocket() {
  return window['go']['client']['Client']['DialSocket']();
}

export function GetAvatar(arg1, arg2) {
  return window['go']['client']['Client']['GetAvatar'](arg1, arg2);
}

export function GetHttpURL() {
  return window['go']['client']['Client']['GetHttpURL']();
}

export function GetSelfAvatar(arg1) {
  return window['go']['client']['Client']['GetSelfAvatar'](arg1);
}

export function GetSocketHistory() {
  return window['go']['client']['Client']['GetSocketHistory']();
}

export function GetUpdate() {
  return window['go']['client']['Client']['GetUpdate']();
}

export function GetUser() {
  return window['go']['client']['Client']['GetUser']();
}

export function LoginToSocket() {
  return window['go']['client']['Client']['LoginToSocket']();
}

export function OpenAvatarPickDialog() {
  return window['go']['client']['Client']['OpenAvatarPickDialog']();
}

export function ReadAndRespond(arg1) {
  return window['go']['client']['Client']['ReadAndRespond'](arg1);
}

export function SendTyping(arg1) {
  return window['go']['client']['Client']['SendTyping'](arg1);
}

export function SetSocket(arg1) {
  return window['go']['client']['Client']['SetSocket'](arg1);
}
