// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mocks} from '../models';

export function ChangeUser(arg1:mocks.PrivateUser):void;

export function DialSocket():Promise<any>;

export function GetAvatar(arg1:string,arg2:number):Promise<string>;

export function GetAvatarRaw(arg1:string,arg2:string,arg3:number):Promise<string>;

export function GetHttpURL():Promise<string>;

export function GetLocation():Promise<mocks.GeoLocation>;

export function GetSelfAvatar(arg1:number):Promise<string>;

export function GetSocketHistory():Promise<Array<string>>;

export function GetUpdate():Promise<mocks.Update>;

export function GetUser():Promise<mocks.PrivateUser>;

export function GetUsers():Promise<Array<mocks.PrivateUser>>;

export function LoginToSocket():void;

export function OpenAvatarPickDialog():Promise<any>;

export function ReadAndRespond(arg1:Array<number>):void;

export function ReconnectToSocket():void;

export function RemoveUser(arg1:mocks.PrivateUser):void;

export function SendTyping(arg1:string):void;

export function SetSocket(arg1:string):void;
