// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mocks} from '../models';

export function DialSocket():Promise<any>;

export function GetSocketHistory():Promise<Array<string>>;

export function GetUser():Promise<mocks.PrivateUser>;

export function LoginToSocket():void;

export function ReadAndRespond(arg1:Array<number>):void;

export function SetSocket(arg1:string):void;
