// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DialSocket() {
  return window['go']['client']['Client']['DialSocket']();
}

export function GetSocketHistory() {
  return window['go']['client']['Client']['GetSocketHistory']();
}

export function ReadAndRespond(arg1) {
  return window['go']['client']['Client']['ReadAndRespond'](arg1);
}
