// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mocks} from '../models';

export function ChangeWorkDir():Promise<string>;

export function GetBuildData():Promise<mocks.Update>;

export function GetReadyToPublish():Promise<boolean>;

export function GetWorkDir():Promise<string>;

export function PNPMBuild():void;

export function PublishRelease(arg1:mocks.Update):Promise<mocks.Update>;

export function SaveBuildData(arg1:mocks.Update):void;

export function TestGCCInstall():Promise<any>;

export function TestWailsInstall():Promise<any>;

export function WailsBuild():void;
