// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeWorkDir():Promise<string>;

export function GetWorkDir():Promise<string>;

export function PNPMBuild():void;

export function TestGCCInstall():Promise<any>;

export function TestWailsInstall():Promise<any>;

export function WailsBuild():void;
