// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeWorkDir() {
  return window['go']['client']['DeveloperClient']['ChangeWorkDir']();
}

export function GetBuildData() {
  return window['go']['client']['DeveloperClient']['GetBuildData']();
}

export function GetReadyToPublish() {
  return window['go']['client']['DeveloperClient']['GetReadyToPublish']();
}

export function GetWorkDir() {
  return window['go']['client']['DeveloperClient']['GetWorkDir']();
}

export function PNPMBuild() {
  return window['go']['client']['DeveloperClient']['PNPMBuild']();
}

export function PublishRelease(arg1) {
  return window['go']['client']['DeveloperClient']['PublishRelease'](arg1);
}

export function SaveBuildData(arg1) {
  return window['go']['client']['DeveloperClient']['SaveBuildData'](arg1);
}

export function TestGCCInstall() {
  return window['go']['client']['DeveloperClient']['TestGCCInstall']();
}

export function TestWailsInstall() {
  return window['go']['client']['DeveloperClient']['TestWailsInstall']();
}

export function WailsBuild() {
  return window['go']['client']['DeveloperClient']['WailsBuild']();
}
