// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {url} from '../models';
import {http} from '../models';
import {mocks} from '../models';
import {client} from '../models';

export function CreateURL(arg1:string):Promise<url.URL>;

export function CreateURLWithAuthorization(arg1:url.URL,arg2:string):Promise<http.Request>;

export function LoginWithEmailAndPassword(arg1:string,arg2:string):Promise<mocks.PrivateUser>;

export function LoginWithToken(arg1:string):Promise<mocks.PrivateUser>;

export function RegisterEmail(arg1:string):Promise<client.HttpResponse>;

export function RegisterLoginWithClient(arg1:mocks.PrivateUser):void;

export function RegisterUser(arg1:string,arg2:string,arg3:string,arg4:string):Promise<client.HttpResponse>;

export function SetAPI(arg1:string):void;

export function SetSecure(arg1:boolean):void;
