// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateURL(arg1) {
  return window['go']['client']['HttpClient']['CreateURL'](arg1);
}

export function RegisterEmail(arg1) {
  return window['go']['client']['HttpClient']['RegisterEmail'](arg1);
}

export function SetAPI(arg1) {
  return window['go']['client']['HttpClient']['SetAPI'](arg1);
}

export function SetSecure(arg1) {
  return window['go']['client']['HttpClient']['SetSecure'](arg1);
}
