// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mocks} from '../models';
import {client} from '../models';

export function AddFriend(arg1:string):Promise<mocks.PublicUser>;

export function CreateGetRequestWithAuthorization(arg1:any,arg2:string):Promise<any>;

export function CreatePostRequestWithAuthorization(arg1:any):Promise<any>;

export function CreatePostRequestWithBodyAndAuthorization(arg1:any,arg2:Promise<any>): Promise<any>;

export function CreateURL(arg1:string):Promise<any>;

export function LoginWithEmailAndPassword(arg1:string,arg2:string):Promise<mocks.PrivateUser>;

export function LoginWithToken(arg1:string):Promise<mocks.PrivateUser>;

export function RegisterEmail(arg1:string):Promise<client.HttpResponse>;

export function RegisterLoginWithClient(arg1:mocks.PrivateUser):void;

export function RegisterUser(arg1:string,arg2:string,arg3:string,arg4:string):Promise<client.HttpResponse>;

export function SetAPI(arg1:string):void;

export function SetSecure(arg1:boolean):void;

export function UploadAvatar(arg1:string):Promise<mocks.PublicUser>;
