// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFriend(arg1) {
  return window['go']['client']['HttpClient']['AddFriend'](arg1);
}

export function GetDevices(arg1) {
  return window['go']['client']['HttpClient']['GetDevices'](arg1);
}

export function GetLatestRelease() {
  return window['go']['client']['HttpClient']['GetLatestRelease']();
}

export function GetLocation() {
  return window['go']['client']['HttpClient']['GetLocation']();
}

export function GetMessagesFromDM(arg1, arg2, arg3) {
  return window['go']['client']['HttpClient']['GetMessagesFromDM'](arg1, arg2, arg3);
}

export function LoginWithEmailAndPassword(arg1, arg2) {
  return window['go']['client']['HttpClient']['LoginWithEmailAndPassword'](arg1, arg2);
}

export function LoginWithToken(arg1) {
  return window['go']['client']['HttpClient']['LoginWithToken'](arg1);
}

export function PublishRelease(arg1) {
  return window['go']['client']['HttpClient']['PublishRelease'](arg1);
}

export function RegisterEmail(arg1) {
  return window['go']['client']['HttpClient']['RegisterEmail'](arg1);
}

export function RegisterLoginWithClient(arg1) {
  return window['go']['client']['HttpClient']['RegisterLoginWithClient'](arg1);
}

export function RegisterUser(arg1, arg2, arg3, arg4) {
  return window['go']['client']['HttpClient']['RegisterUser'](arg1, arg2, arg3, arg4);
}

export function SetAPI(arg1) {
  return window['go']['client']['HttpClient']['SetAPI'](arg1);
}

export function SetSecure(arg1) {
  return window['go']['client']['HttpClient']['SetSecure'](arg1);
}

export function UploadAvatar(arg1) {
  return window['go']['client']['HttpClient']['UploadAvatar'](arg1);
}
