// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mocks} from '../models';

export function GetRelations():Promise<mocks.RelationshipStruct>;

export function InternalAddRelation(arg1:string,arg2:mocks.PublicUser):Promise<Error>;

export function RequestFriend(arg1:string):Promise<mocks.PublicUser>;
