// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRelations() {
  return window['go']['client']['RelationshipManager']['GetRelations']();
}

export function InternalAddRelation(arg1, arg2) {
  return window['go']['client']['RelationshipManager']['InternalAddRelation'](arg1, arg2);
}

export function RequestFriend(arg1) {
  return window['go']['client']['RelationshipManager']['RequestFriend'](arg1);
}
