// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mocks} from '../models';

export function AcceptFriend(arg1:string):Promise<mocks.PublicUser>;

export function ClearRelations():void;

export function FindRelation(arg1:number):Promise<mocks.PublicUser>;

export function GetRelations():Promise<mocks.RelationshipStruct>;

export function RemoveFriend(arg1:string):void;

export function RequestFriend(arg1:string):Promise<mocks.PublicUser>;
