// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mocks} from '../models';
import {map[int64]mocks} from '../models';

export function AcceptFriend(arg1:string):Promise<mocks.PublicUser>;

export function ClearRelations():void;

export function FindRelation(arg1:mocks.PublicUser):Promise<map[int64]mocks.PublicUser>;

export function GetRelations():Promise<mocks.RelationshipStruct>;

export function InternalAddRelation(arg1:string,arg2:mocks.PublicUser):Promise<Error>;

export function RequestFriend(arg1:string):Promise<mocks.PublicUser>;
