// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptFriend(arg1) {
  return window['go']['client']['RelationshipManager']['AcceptFriend'](arg1);
}

export function ClearRelations() {
  return window['go']['client']['RelationshipManager']['ClearRelations']();
}

export function FindRelation(arg1) {
  return window['go']['client']['RelationshipManager']['FindRelation'](arg1);
}

export function FindRelations(arg1) {
  return window['go']['client']['RelationshipManager']['FindRelations'](arg1);
}

export function GetRelations() {
  return window['go']['client']['RelationshipManager']['GetRelations']();
}

export function InternalAddRelation(arg1, arg2) {
  return window['go']['client']['RelationshipManager']['InternalAddRelation'](arg1, arg2);
}

export function RemoveFriend(arg1) {
  return window['go']['client']['RelationshipManager']['RemoveFriend'](arg1);
}

export function RequestFriend(arg1) {
  return window['go']['client']['RelationshipManager']['RequestFriend'](arg1);
}
